const menu=document.querySelector('.menu');const nav=document.querySelector('#nav');menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open))});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}));
const cards=[...document.querySelectorAll('.products article')];const filters=[...document.querySelectorAll('[data-filter]')];const search=document.querySelector('#product-search');const empty=document.querySelector('.no-results');let category='all';
function applyFilters(){const query=search.value.trim().toLowerCase();let shown=0;cards.forEach(card=>{const matchesCategory=category==='all'||card.dataset.category===category;const matchesText=card.dataset.name.toLowerCase().includes(query)||card.textContent.toLowerCase().includes(query);const show=matchesCategory&&matchesText;card.classList.toggle('hidden',!show);if(show)shown++});empty.hidden=shown>0}
filters.forEach(button=>button.addEventListener('click',()=>{category=button.dataset.filter;filters.forEach(b=>b.classList.toggle('active',b===button));applyFilters()}));search.addEventListener('input',applyFilters);
document.querySelectorAll('[data-category-link]').forEach(link=>link.addEventListener('click',()=>{category=link.dataset.categoryLink;filters.forEach(b=>b.classList.toggle('active',b.dataset.filter===category));applyFilters()}));
document.querySelectorAll('.product-wa').forEach(link=>{const message=`Hello Mboky Holdings, I would like the current sizes, price and availability for ${link.dataset.product}.`;link.href=`https://wa.me/254731780253?text=${encodeURIComponent(message)}`;link.target='_blank';link.rel='noopener'});
document.querySelector('#quote-form').addEventListener('submit',event=>{event.preventDefault();const data=new FormData(event.currentTarget);const message=`Hello Mboky Holdings, my name is ${data.get('name')}. My phone number is ${data.get('phone')}. I am interested in ${data.get('product')}. Details: ${data.get('details')||'Please share current prices and availability.'}`;window.open(`https://wa.me/254731780253?text=${encodeURIComponent(message)}`,'_blank','noopener')});

const copyrightYear=document.querySelector('#copyright-year');if(copyrightYear)copyrightYear.textContent=String(new Date().getFullYear());


